abstract: ~
author: The Pugs Team <perl6-compiler@perl.org>.
distribution_type: module
generated_by: Module::Install version 0.63
license: perl
name: v6-pugs
no_index:
  directory:
    - inc
    - t
recommends:
  Perl::Tidy: 0
requires:
  Module::Compile: 0.16
  Pugs::Compiler::Rule: 0.06
  perl: 5.6.0
version: 0.001
